name: Actions Workflow

on: [push]

jobs:
  run-gitlub-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files
        run: |
          pwd
          ls -a
      # - name: Simple JS Actions
      #   id: greet
      #   uses: actions/hello-world-javascript-actions@v1
      #   with:
      #     who-to-greet: Uros
      # - name: Log Greeting Time
      #   run: echo "{{ steps.greet.outputs.time }}"